services:

  owncloud:
    image: owncloud/server:latest
    environment:
      - OWNCLOUD_ADMIN_USERNAME=sxe_admin
      - OWNCLOUD_ADMIN_PASSWORD=sxe_admin_password
      - OWNCLOUD_DB_NAME=sxe_owncloud_db
      - OWNCLOUD_DB_USERNAME=sxe_user_db
      - OWNCLOUD_DB_PASSWORD=sxe_user_password_db
    volumes:
      - oc_vol:/mnt/data #volumen para persistir los datos
    depends_on:
      - mariadb #indica la dependencia de mariadb
    ports:
      - 8080:8080

  mariadb:
    image: mariadb:11.1
    environment:
      - MYSQL_ROOT_PASSWORD=sxe_root_password
      - MYSQL_DATABASE=sxe_owncloud_db
      - MYSQL_USER=sxe_user_db
      - MYSQL_PASSWORD=sxe_user_password_db
    volumes:
      - db_vol:/var/lib/mysql

  adminer:
    image: adminer:latest
    environment:
      - ADMINER_DESIGN=dracula #selección de diseño
    ports:
      - 8081:8080 #mapeo de puertos

volumes:
  db_vol: #volumen para los datos de mariadb
  oc_vol: #volumen para los datos de owncloud
